### ISSUE TITLE
Does not return the value of the attribute in the function getEntityAttributeValue

### ISSUE THREAD

**Issue by racf** [cenidetiot/OCB.jsLibrary#1]
Hello...!
Implement the function of the ocb-sender module (getEntityAttributeValue) and execute the following code:
cb.getEntityAttributeValue("Device_Smartphone_40bbcd9c6cae67c0", "batteryLevel")
.then((result) => console.log(result))
.catch((err) => console.log(err))

The response result is as follows:
{ statusCode: 200,
  message: 'Se estableció conexión con el ContextBroker' }
{ value: Promise { <pending> }, attribute: 'batteryLevel' }

They could help me ... because the value does not return the result.

**Comment by toodaniels** [comment]
Hi Fer thanks for the comment, it was solved in the current version **2.1.1**
